In [ ]:
import tensorflow as tf
import numpy as np

print(f"Tf version: {tf.__version__}\n")

I0000 00:00:1790780941.285973    3517 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Tf version: 2.21.0



In [11]:
t = tf.constant([[1., 2., 3.],[4., 5., 6.]])
print(t)
print(t.shape)
print(t.dtype)
print()
print(t+10)
print(tf.square(t))
print(t @ tf.transpose(t))
print()
a = np.array([1,2,3])
t_from_np = tf.constant(a)
print(t_from_np)
print(t_from_np.numpy())
print()
t_float = tf.constant(2.0, dtype=tf.float32)
t_int = tf.constant(3, dtype=tf.int32)

# print('Попробую сломать типизацию:')
# try: 
#     res = t_float + t_int
# except TypeError as e:
#     print('Ошибка типов!')
#     print(e)

res_fix = t_float + tf.cast(t_int, tf.float32)
print(res_fix.numpy())

v = tf.Variable([[1., 2.], [3., 4.]])
print("\nИзначальная переменная v:\n", v.numpy())
v.assign(v * 2)
print("Переменная v после v.assign(v * 2):\n", v.numpy())
v[0, 1].assign(42.0)
print("Переменная v после точечного изменения:\n", v.numpy())

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
[1 2 3]

5.0

Изначальная переменная v:
 [[1. 2.]
 [3. 4.]]
Переменная v после v.assign(v * 2):
 [[2. 4.]
 [6. 8.]]
Переменная v после точечного изменения:
 [[ 2. 42.]
 [ 6.  8.]]
